version: "3"
services:
  nginx:
    image: europeana/portaljs-nginx
    build:
      context: ./nginx
    ports:
      - "443:443"
      - "80:80"
  app:
    image: europeana/portaljs-app
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    expose:
      - "8080"
    env_file:
     - ../.env
