version: "3"
services:
  nginx:
    image: europeana/portaljs-nginx
    build:
      context: ./nginx
    network_mode: host
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NGINX_PROXY_URL
