# Cloud Foundry manifest
---
buildpack: nodejs_buildpack
command: cservice --restartOnMemUsage 268435456 --cli false server/index.js
memory: 1024M
health-check-type: process
# health-check-http-endpoint: /robots.txt
stack: cflinuxfs3
env:
  CONSOLA_LEVEL: info
  HOST: 0.0.0.0
  OPTIMIZE_MEMORY: true
