name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

env:
  CF_API: https://api.eu-de.bluemix.net
  CF_ORG: europeana-dev
  CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
  CF_SPACE: dev
  CF_USERNAME: apikey
  CHROMEDRIVER_SKIP_DOWNLOAD: false
  CTF_CDA_ACCESS_TOKEN: ${{ secrets.CTF_CDA_ACCESS_TOKEN }}
  CTF_ENVIRONMENT_ID: test
  CTF_SPACE_ID: ${{ secrets.CTF_SPACE_ID }}
  DISQUS_SHORTNAME:  ${{ secrets.DISQUS_SHORTNAME }}
  EUROPEANA_ANNOTATION_API_KEY: ${{ secrets.EUROPEANA_ANNOTATION_API_KEY }}
  EUROPEANA_ENTITY_API_KEY: ${{ secrets.EUROPEANA_ENTITY_API_KEY }}
  EUROPEANA_RECORD_API_KEY: ${{ secrets.EUROPEANA_RECORD_API_KEY }}
  GECKODRIVER_SKIP_DOWNLOAD: true
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${GITHUB_RUN_ID}
    - run: echo ${GITHUB_ACTOR}
    - run: echo ${GITHUB_REPOSITORY}
    - run: echo ${GITHUB_REF}
    - run: echo ${GITHUB_HEAD_REF}
    - run: echo ${GITHUB_BASE_REF}
    - run: echo ${GITHUB_SHA}
    - run: cat ${GITHUB_EVENT_PATH}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: .nuxt
        path: .nuxt/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/download-artifact@v2
    - run: npm run lint
    - run: npm run stylelint
    - run: npm run test:unit
    - run: npx size-limit

  e2e:
    needs: build
    if: github.event_name	== 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/download-artifact@v2
    - run: npm run test:e2e:ci

  deploy:
    needs: test
    if: github.event_name	== 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
    - run: wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
    - run: echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
    - run: apt-get -q update && apt-get -yq install cf-cli
    - run: cf install-plugin blue-green-deploy -f -r CF-Community
    - run: cf install-plugin app-autoscaler-plugin -f -r CF-Community
    - run: cf plugins
    - run: cf login -a ${CF_API} -u ${CF_USERNAME} -p "${CF_PASSWORD}" -o ${CF_ORG} -s ${CF_SPACE}
    - run: cf target
